-- MySQL Script generated by MySQL Workbench
-- Wed Sep  2 09:55:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema authorization
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema authorization
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `authorization` DEFAULT CHARACTER SET utf8 ;
USE `authorization` ;

-- -----------------------------------------------------
-- Table `authorization`.`t_auth_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authorization`.`t_auth_user` ;

CREATE TABLE IF NOT EXISTS `authorization`.`t_auth_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `context` VARCHAR(1024) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `authorization`.`t_auth_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authorization`.`t_auth_resource` ;

CREATE TABLE IF NOT EXISTS `authorization`.`t_auth_resource` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resourceType` VARCHAR(64) NOT NULL DEFAULT '',
  `resourceCode` VARCHAR(64) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  INDEX `resource_index` (`resourceType` ASC, `resourceCode` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `authorization`.`t_auth_resource_parent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authorization`.`t_auth_resource_parent` ;

CREATE TABLE IF NOT EXISTS `authorization`.`t_auth_resource_parent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resourceId` INT NOT NULL DEFAULT 0,
  `parentId` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `resource_foreign_key_idx` (`resourceId` ASC) VISIBLE,
  INDEX `resource_parent_key_idx` (`parentId` ASC) VISIBLE,
  CONSTRAINT `resource_key`
    FOREIGN KEY (`resourceId`)
    REFERENCES `authorization`.`t_auth_resource` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `resource_parent_key`
    FOREIGN KEY (`parentId`)
    REFERENCES `authorization`.`t_auth_resource` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `authorization`.`t_auth_resource_relative`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authorization`.`t_auth_resource_relative` ;

CREATE TABLE IF NOT EXISTS `authorization`.`t_auth_resource_relative` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resourceId` INT NOT NULL DEFAULT 0,
  `relativeId` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `resource_key_idx` (`resourceId` ASC) VISIBLE,
  INDEX `resource_relative_key_idx` (`relativeId` ASC) VISIBLE,
  CONSTRAINT `resource_key`
    FOREIGN KEY (`resourceId`)
    REFERENCES `authorization`.`t_auth_resource` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `resource_relative_key`
    FOREIGN KEY (`relativeId`)
    REFERENCES `authorization`.`t_auth_resource` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `authorization`.`t_auth_authorization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authorization`.`t_auth_authorization` ;

CREATE TABLE IF NOT EXISTS `authorization`.`t_auth_authorization` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resourceId` INT NOT NULL DEFAULT 0,
  `userId` INT NOT NULL DEFAULT 0,
  `isHeritable` TINYINT NOT NULL DEFAULT 0,
  `isUpdatable` TINYINT NOT NULL DEFAULT 0,
  `isDeleteable` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `resource_key_idx` (`resourceId` ASC) VISIBLE,
  INDEX `user_key_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `resource_key`
    FOREIGN KEY (`resourceId`)
    REFERENCES `authorization`.`t_auth_resource` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_key`
    FOREIGN KEY (`userId`)
    REFERENCES `authorization`.`t_auth_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `authorization`.`t_auth_authorization_operation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authorization`.`t_auth_authorization_operation` ;

CREATE TABLE IF NOT EXISTS `authorization`.`t_auth_authorization_operation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `authorizationId` INT NOT NULL DEFAULT 0,
  `operation` VARCHAR(64) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  INDEX `authorization_key_idx` (`authorizationId` ASC) VISIBLE,
  CONSTRAINT `authorization_key`
    FOREIGN KEY (`authorizationId`)
    REFERENCES `authorization`.`t_auth_authorization` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `authorization`.`t_auth_user_relative`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authorization`.`t_auth_user_relative` ;

CREATE TABLE IF NOT EXISTS `authorization`.`t_auth_user_relative` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL DEFAULT 0,
  `relativeId` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `user_key_idx` (`userId` ASC) VISIBLE,
  INDEX `user_relative_key_idx` (`relativeId` ASC) VISIBLE,
  CONSTRAINT `user_key`
    FOREIGN KEY (`userId`)
    REFERENCES `authorization`.`t_auth_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_relative_key`
    FOREIGN KEY (`relativeId`)
    REFERENCES `authorization`.`t_auth_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
